---
development:
  cloud_name: ms-someone-dev
  api_key: <%= ENV['MISS_SUZUKI_CLOUDINARY_API_KEY_DEV'] %>
  api_secret: <%= ENV['MISS_SUZUKI_CLOUDINARY_API_SECRET_DEV'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: miss-someone
  api_key: <%= ENV['MISS_SUZUKI_CLOUDINARY_API_KEY_PROD'] %>
  api_secret: <%= ENV['MISS_SUZUKI_CLOUDINARY_API_SECRET_PROD'] %>
  enhance_image_tag: true
  static_image_support: true
staging:
  cloud_name: miss-someone
  api_key: <%= ENV['MISS_SUZUKI_CLOUDINARY_API_KEY_PROD'] %>
  api_secret: <%= ENV['MISS_SUZUKI_CLOUDINARY_API_SECRET_PROD'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ms-someone-dev
  api_key: <%= ENV['MISS_SUZUKI_CLOUDINARY_API_KEY_DEV'] %>
  api_secret: <%= ENV['MISS_SUZUKI_CLOUDINARY_API_SECRET_DEV'] %>
  enhance_image_tag: true
  static_image_support: false
