---
development:
  cloud_name: ms-someone
  api_key: '669875357541857'
  api_secret: Qy6XrGA1I6-yLKWKl88zwLdY9ko
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ms-someone
  api_key: '669875357541857'
  api_secret: Qy6XrGA1I6-yLKWKl88zwLdY9ko
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ms-someone
  api_key: '669875357541857'
  api_secret: Qy6XrGA1I6-yLKWKl88zwLdY9ko
  enhance_image_tag: true
  static_image_support: false
