user_type:
  normal: 1
  contestant: 2
sex:
  male: 1
  female: 2
  unknown: 3
current_group_id: 2
current_open_group_id: 3 # 現在公開中のグループID最大値
contestant:
  preopen_count: 3 # プレオープンで公開する参加者の数
  default_blur: 500
link_type:
  facebook: 1
  twitter: 2
  instagram: 3
  blog: 4
  movie: 5
  web: 6
vote:
  token_name: nekot_etov
  daily_limit:
    not_logined: 3
    logined: 10
contestant_image_max: 12

# CircleCIからwebhookでデプロイする際のデプロイキー
deploy_info:
  key: MJweV0EYMHJQXECqy3PlBbCYwRZ7g6rNhtM0Gl5U7bY0WHzL5hXOLeWtiKKa
  vcs_url: 'https://github.com/miss-someone/miss-suzuki'
  command: "/home/webmaster/bin/miss-suzuki-deploy.sh"
  slack_webhook_url: 'https://hooks.slack.com/services/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'
